### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by Poussinou** [conorH22/AttackOfOzones#1]
Hi,

Would it be possible to have build instructions for this project? It would really be useful to build this game for [F-Droid](https://gitlab.com/fdroid/rfp/issues/401).

**Comment by conorH22** [comment]
Attack of Ozones is listed on the google play store [link](https://play.google.com/store/apps/details?id=com.conorH22.AttackOfOzonesv2&hl=en&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)

**Comment by Poussinou** [comment]
Yes, but F-Droid build the applications directly from sources, that's why we need some build instructions.

**Comment by conorH22** [comment]
GitHub has size limit(100mb) or no more than hundred files in one folder on
files being uploaded to the repo. Unless I compress the project folder.

What files does  F-droid need to build application directly from source ?

**Comment by Poussinou** [comment]
@Rudloff I think you know better than me in that case.

**Comment by Rudloff** [comment]
I'm not sure how this project builds but we would need either:
* A Makefile or some sort of automated script that builds the app.
* A series of commands we can run to build the app.

**Comment by conorH22** [comment]
I will create build file and upload to the repo.

**Comment by conorH22** [comment]
I have uploaded a build instructions file on this repo. [link](https://github.com/conorH22/AttackOfOzones/blob/master/Build.md)

**Comment by Rudloff** [comment]
Thanks for the instructions!
I tried to run `cocos compile` but it wants a `.cocos-project.json` file:
```
/home/pierre/www/AttackOfOzones/.cocos-project.json is not found.
```

Is this file missing from the repository?

**Comment by conorH22** [comment]
Yeah it's missing, as it's in Cocos folder. I will have to zip the project folder and upload it to the repo. The
original folder size is around 2-4 GB. The current repo only has the class
files.

Alternatively you can download Cocos2dx and use Cocos new command and use
the class files and resources.

**Comment by Rudloff** [comment]
Wow, this is huge. Are you talking about the `proj.android` folder? I think with [this kind of folder](https://github.com/MakeSchool/SushiNeko-Cpp/tree/master/proj.android) we could build the app with Ant without having to install Cocos.

**Comment by conorH22** [comment]
The overall project folder which includes resources, Cocos and proj.android.

**Comment by conorH22** [comment]
proj.android file size is 1.12gb.

**Comment by Rudloff** [comment]
Wow, that's really huge! Is that only source code and assets or does it also include build artifacts that you could ignore?

**Comment by conorH22** [comment]
Looking at the file structure. it's the debug and signed APK.  The apks is 80mb per file in the project.android.  With GitHub size allowances 25mb per file/folder and max of 100 files in one folder.

**Comment by Rudloff** [comment]
You don't need to include APKs in the repository, only files necessary to build them.

**Comment by conorH22** [comment]
I have the proj.android file uploaded see the latest commit  [here](https://github.com/conorH22/AttackOfOzones/commit/4290a759fede6e3ba041a0fc145cc309378f9b2d)

**Comment by Rudloff** [comment]
Thanks, I managed to use these files to build the APK with Ant.
However it still needs `libMygame.so`:
```
06-08 15:50:37.270  4726  4726 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.conorH22.AttackOfOzonesv2-2/base.apk"],nativeLibraryDirectories=[/data/app/com.conorH22.AttackOfOzonesv2-2/lib/arm, /data/app/com.conorH22.AttackOfOzonesv2-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]] couldn't find "libMyGame.so"
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:114)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:140)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6285)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:150)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-08 15:50:37.270  4726  4726 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-08 15:50:37.274  2184  3371 W ActivityManager:   Force finishing activity com.conorH22.AttackOfOzonesv2/org.cocos2dx.cpp.AppActivity
```
I suppose I have to build it separately with Cocos but I don't have time to investigate further right now.

**Comment by Rudloff** [comment]
It seems this app can't be built with a recent SDK anymore:
```
Buildfile: /home/pierre/www/AttackOfOzones/proj.android/build.xml

BUILD FAILED
/home/pierre/www/AttackOfOzones/proj.android/build.xml:81: Cannot find /home/pierre/www/android-sdk/tools/ant/build.xml imported from /home/pierre/www/AttackOfOzones/proj.android/build.xml

Total time: 0 seconds
```

The ant build system is deprecated and apps are now typically built with Gradle.
It looks like Cocos supports that since v3.15.

@conorH22 Any chance you could switch to a Gradle-based build?
(Cocos documentation only talks about Android Studio, but Android Studio projects can also be built from the CLI with Gradle.)
